apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: gitstars.app.example.com
spec:
  group: app.example.com
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: GitStar is the Schema for the gitstars API
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
                    of an object. Servers should convert recognized schemas to the latest
                    internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
                    object represents. Servers may infer this from the endpoint the client
                    submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: GitStarSpec defines the desired state of GitStar
              type: object
            status:
              description: GitStarStatus defines the observed state of GitStar
              type: object
          type: object
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Repo
          type: string
          jsonPath: .spec.repo_name
        - name: Star
          type: integer
          jsonPath: .status.star_number
        - name: updatedAt
          type: date
          jsonPath: .status.updated_at
        - name: failedReason
          type: string
          jsonPath: .status.failed_reason
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
  names:
    kind: GitStar
    listKind: GitStarList
    plural: gitstars
    singular: gstar